In [1]:
import numpy as  np 



In [4]:
#creating an array
arr = np.array([10, 20, 30, 40, 50, 60]) 

#  np.zeros() 
zeros_arr = np.zeros((3, 3)) 

#  np.ones() 
ones_arr = np.ones((2, 4)) 

#  np.arange() 
range_arr = np.arange(0, 20, 2) 

print("Array:\n", arr)
print("Zeros:\n", zeros_arr)
print("Ones:\n", ones_arr)
print("Range:\n", range_arr)

Array:
 [10 20 30 40 50 60]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range:
 [ 0  2  4  6  8 10 12 14 16 18]


In [5]:
#SLICING
sliced = arr[2:5]
print("Sliced Array from index 2 to 4(30, 40, 50):\n", sliced)

Sliced Array from index 2 to 4(30, 40, 50):
 [30 40 50]


In [7]:
#MATHEMATICAL OPERATIONS
a, b = np.array([1, 2, 3]), np.array([4, 5, 6])
addition = np.add(a, b)
multiplication = a * b
dot_product = np.dot(a, b)

print("Addition:\n", addition)
print("Multiplication:\n", multiplication)      
print("Dot Product:\n", dot_product)

Addition:
 [5 7 9]
Multiplication:
 [ 4 10 18]
Dot Product:
 32


In [8]:
#STATISTICAL ANALYSIS
mean_value=np.mean(arr)
median_value=np.median(arr)
std_deviation=np.std(arr)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)
#BROADCASTING
broadcasted = arr + 50
print("Broadcasted Array (each element +50):\n", broadcasted)

Mean: 35.0
Median: 35.0
Standard Deviation: 17.07825127659933
Broadcasted Array (each element +50):
 [ 60  70  80  90 100 110]
